"""Chunk 3.1: one packet, both ways, and every way the conversion can lie.

`codec` is the only place in the workspace that knows both the dataclass the
routing logic reasons about and the message that crosses the seam. That makes
it the one place a field can be silently renamed, widened, reordered or
dropped, and every one of those produces a run where the radio works and the
delivered set is wrong.

So the load bearing test here is the round trip: an arbitrary packet encoded
and decoded again must be the packet that went in, field for field, and the
comparison is against `PACKET_FIELDS` rather than against a list written here,
because a list written here would stop covering a field the moment one was
added.

`decode` never raises, and that is a decision rather than an omission. It runs
inside the link layer's receive callback, and a raise there takes the radio
down for the whole swarm because one node emitted something malformed. Every
malformed shape below is checked to return None instead.

    colcon test --packages-select uavx_comms

Needs the overlay: uavx_msgs is generated code and there is no source tree
fallback for a message type.
"""

import math

import pytest

from uavx_comms import packet as pk, params

# Before `codec` and not after it. `codec` imports the message package at its
# own module scope, so importing it first raises ModuleNotFoundError during
# collection and the skip below never runs. Chunk 3.1 wrote these two the
# other way round: under colcon the overlay is sourced and both work, so the
# gate was green while `pytest uavx_ws/src/uavx_comms/test/` on a bare
# checkout could not collect the file at all.
SwarmPacket = pytest.importorskip(
    "uavx_msgs.msg",
    reason="uavx_msgs is generated by the build; there is no source fallback"
).SwarmPacket

from uavx_comms import codec                        # noqa: E402

# Built per index, never written out. scripts/check_seam.sh counts distinct
# vehicle endpoint literals per file and that rule covers tests.
VEHICLES = tuple(f"uav_{n}" for n in range(1, 5))
ORIGIN = VEHICLES[3]
RELAY = VEHICLES[1]


def observation():
    return pk.observation(ORIGIN, 7, 12.5)


def hello():
    return pk.control(ORIGIN, pk.KIND_HELLO, 3.25,
                      {"position": [475.0, -75.0, 60.0], "role": 0},
                      sequence=4)


# ------------------------------------------------------------ round trip
@pytest.mark.parametrize("build", [observation, hello])
def test_a_packet_survives_the_round_trip_field_for_field(build):
    source = build()
    back = codec.decode(codec.encode(source))
    assert back is not None
    for name in pk.PACKET_FIELDS:
        assert getattr(back, name) == getattr(source, name), name


def test_the_round_trip_covers_every_field_the_packet_declares():
    """A field added to Packet without being carried here fails this."""
    source = observation()
    back = codec.decode(codec.encode(source))
    assert set(pk.PACKET_FIELDS) == set(vars(source))
    assert vars(back) == vars(source)


def test_an_observation_keeps_its_frozen_payload_size():
    message = codec.encode(observation())
    assert len(message.payload) == params.OBSERVATION_BYTES


def test_identity_is_the_pair_and_survives_the_wire():
    source = observation()
    back = codec.decode(codec.encode(source))
    assert back.identity() == (ORIGIN, 7)
    assert back.identity_str() == source.identity_str()


def test_the_path_is_copied_and_not_shared():
    source = hello()
    source.path = [ORIGIN, RELAY]
    back = codec.decode(codec.encode(source))
    back.path.append("gcs")
    assert source.path == [ORIGIN, RELAY]


def test_every_kind_crosses_the_wire_as_itself():
    for kind in pk.KIND_NAMES:
        if kind == pk.KIND_OBSERVATION:
            source = pk.observation(ORIGIN, 1, 0.0)
        else:
            source = pk.control(ORIGIN, kind, 0.0, {"n": 1})
        assert codec.decode(codec.encode(source)).kind == kind


# ------------------------------------------------------- encode refuses
def test_a_kind_the_message_does_not_define_is_refused():
    source = observation()
    source.kind = 9
    with pytest.raises(codec.CodecError, match="kind"):
        codec.encode(source)


@pytest.mark.parametrize("sequence", [-1, codec.UINT32_MAX + 1])
def test_a_sequence_outside_uint32_is_refused(sequence):
    source = observation()
    source.sequence = sequence
    with pytest.raises(codec.CodecError, match="sequence"):
        codec.encode(source)


def test_a_boolean_sequence_is_refused():
    source = observation()
    source.sequence = True
    with pytest.raises(codec.CodecError, match="sequence"):
        codec.encode(source)


def test_a_hop_count_outside_uint8_is_refused():
    source = observation()
    source.hop_count = codec.UINT8_MAX + 1
    with pytest.raises(codec.CodecError, match="hop_count"):
        codec.encode(source)


def test_an_empty_origin_is_refused_because_identity_needs_it():
    source = observation()
    source.origin_id = ""
    with pytest.raises(codec.CodecError, match="origin_id"):
        codec.encode(source)


def test_an_empty_hop_in_the_path_is_refused():
    source = hello()
    source.path = [ORIGIN, ""]
    with pytest.raises(codec.CodecError, match="path"):
        codec.encode(source)


def test_an_observation_whose_payload_is_not_bytes_is_refused():
    source = observation()
    source.payload = {"not": "bytes"}
    with pytest.raises(codec.CodecError, match="observation"):
        codec.encode(source)


def test_a_control_body_that_is_not_json_is_refused():
    source = pk.control(ORIGIN, pk.KIND_ROLE, 0.0, {"when": object()})
    with pytest.raises(codec.CodecError, match="JSON"):
        codec.encode(source)


def test_a_control_body_carrying_nan_is_refused():
    # json.dumps writes a bare NaN by default, which is not JSON and which no
    # other reader would accept back.
    source = pk.control(ORIGIN, pk.KIND_ROLE, 0.0, {"d": math.nan})
    with pytest.raises(codec.CodecError, match="JSON"):
        codec.encode(source)


def test_a_control_body_over_the_limit_is_refused():
    source = pk.control(ORIGIN, pk.KIND_LSA, 0.0,
                        {"pad": "x" * (codec.CONTROL_PAYLOAD_MAX_BYTES + 1)})
    with pytest.raises(codec.CodecError, match="limit"):
        codec.encode(source)


# ------------------------------------------------------- decode refuses
def test_an_unknown_kind_on_the_wire_decodes_to_nothing():
    message = codec.encode(observation())
    message.kind = 9
    assert codec.decode(message) is None


def test_an_empty_origin_on_the_wire_decodes_to_nothing():
    message = codec.encode(observation())
    message.origin_id = ""
    assert codec.decode(message) is None


def test_a_control_body_that_is_not_utf8_decodes_to_nothing():
    message = codec.encode(hello())
    message.payload = [0xFF, 0xFE, 0xFD]
    assert codec.decode(message) is None


def test_a_control_body_that_is_not_json_decodes_to_nothing():
    message = codec.encode(hello())
    message.payload = list(b"{definitely not json")
    assert codec.decode(message) is None


def test_something_that_is_not_a_message_at_all_decodes_to_nothing():
    assert codec.decode(object()) is None
    assert codec.decode(None) is None


def test_decode_returns_rather_than_raises_on_every_broken_shape():
    """The property that keeps one bad emitter from taking the radio down.

    Stated as "no exception escaped and the result was a Packet or None",
    which is falsifiable. An earlier spelling of this asserted
    `result in (None,) or True`, which is a tautology and would have passed
    against a codec that raised on everything, so it is written out.
    """
    message = codec.encode(hello())
    broken_payloads = ([0xFF], list(b"nope"), [], list(b"[1, 2"),
                       bytes([0x80, 0x81]))
    for broken in broken_payloads:
        message.payload = list(broken)
        try:
            result = codec.decode(message)
        except Exception as exc:                       # noqa: BLE001
            pytest.fail(f"decode raised {exc!r} on payload {broken!r}; the "
                        f"link layer calls this inside a subscription "
                        f"callback and a raise there ends the radio for "
                        f"every node")
        assert result is None or isinstance(result, pk.Packet)

    for wrong_type in (object(), None, 42, "a packet"):
        try:
            assert codec.decode(wrong_type) is None
        except Exception as exc:                       # noqa: BLE001
            pytest.fail(f"decode raised {exc!r} on {wrong_type!r}")
