"""Chunk 3.6: turning rendered frames into the clip the submission carries.

The video is a deliverable and this stack has exactly one way to produce one.
`gzclient` has taken this WSL distribution down three times and is never
launched, so there is no window to capture; the frames have to come from a
camera sensor `gzserver` renders itself, on a ROS image topic, into a file.

Four decisions, and the first two are the ones that decide whether the clip
tells the truth.

**Frames land on disk and are encoded once, afterwards.** The obvious design
pipes frames straight into ffmpeg, and it cannot work here: ffmpeg has to be
told the input frame rate before the first frame, and the real rate is not
known until the last one. Software OpenGL renders this camera at about 7 Hz
against a requested 10, so a clip declared at the nominal rate plays about
1.4 times too fast. A demo video that misrepresents how fast the swarm flies
is worse than no demo video.

**The rate is measured in simulated time.** Every other `_s` in the run
record is, the frames carry the sim time they arrived at, and a clip timed
against wall time would be a clip of a different clock from the one the
record describes.

**The frames are stored raw rather than compressed.** They are written from
inside the runner's own spin loop, which also drains four MAVLink links and
samples poses at 20 Hz. Compressing a 960 by 540 frame in Python costs tens
of milliseconds and doing it seven times a second would slow the loop that
measures the run. A write is a memcpy. The intermediate is large and it is
deleted as soon as the clip exists.

**The overlay is checked, not trusted.** It is the run id, and it goes into
an ffmpeg filter string where a colon or a backslash would change what the
filter means. Anything outside a conservative alphabet is refused rather than
escaped, because the id is generated by this repository and has no business
carrying either.
"""

from __future__ import annotations

import math
import re
from pathlib import Path
from typing import Sequence

# The topic the world's camera publishes on. worlds/uavx_record.world puts the
# plugin in the /uavx_record namespace with camera_name `view`, and
# gazebo_ros_camera builds the topic from the two.
IMAGE_TOPIC = "/uavx_record/view/image_raw"

# The node that plugin creates, as scripts/seam_manifests.json has to name it.
CAMERA_NODE = "/uavx_record/uavx_camera_plugin"

# The world the launcher loads for a recording run, and only for one.
RECORD_WORLD = "uavx_record"

# One file, appended to frame by frame. ffmpeg reads it as rawvideo, so there
# is no numbering to leave a gap in and a dropped frame shortens the clip
# rather than truncating it at the gap.
RAW_NAME = "frames.rgb"

# The only encoding the camera is configured to produce. Anything else means
# the world was edited and the writer below would be packing bytes it has not
# been told the layout of.
ENCODING = "rgb8"
BYTES_PER_PIXEL = 3

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

# Playback rate of the finished clip. Independent of the capture rate: the
# capture rate decides how many frames cover a second of simulated time and
# this decides how smoothly they are played back.
OUTPUT_FPS = 25

# A run id, and nothing that could change what an ffmpeg filter string means.
OVERLAY_RE = re.compile(r"^[A-Za-z0-9_.-]{1,120}$")

# Below this the clip is not a video of anything. Two frames a second over a
# minute is already a slideshow, and a rehearsal that passed on one would be
# telling week 4 that the capture path works.
MIN_CAPTURE_HZ = 2.0


class RecorderError(RuntimeError):
    """A capture that cannot honestly produce a clip, naming the reason."""


def frame_bytes(width: int, height: int) -> int:
    if width < 1 or height < 1:
        raise RecorderError(f"a {width}x{height} frame is not an image")
    return width * height * BYTES_PER_PIXEL


def raw_path(frames_dir) -> Path:
    return Path(frames_dir) / RAW_NAME


def as_rgb(encoding: str, data: Sequence[int], width: int, height: int,
           step: int) -> bytes:
    """The image message's payload as tightly packed rgb8.

    `step` is the row stride and is not always three times the width. A
    reader that assumes it is produces a picture that shears, which on a
    static camera looks like a rendering fault rather than a reader fault.
    """
    if encoding != ENCODING:
        raise RecorderError(
            f"the camera is publishing {encoding!r} and this reader packs "
            f"{ENCODING!r}. worlds/{RECORD_WORLD}.world asks for R8G8B8")
    row = width * BYTES_PER_PIXEL
    if row < 1 or height < 1:
        raise RecorderError(f"a {width}x{height} frame is not an image")
    if step < row:
        raise RecorderError(
            f"a row of {width} rgb8 pixels is {row} bytes and the message "
            f"says its stride is {step}")
    raw = bytes(data)
    if len(raw) < step * height:
        raise RecorderError(
            f"the message carries {len(raw)} bytes and {step * height} were "
            f"promised by its own stride and height")
    if step == row:
        return raw[:row * height]
    return b"".join(raw[y * step:y * step + row] for y in range(height))


def capture_rate(frames: int, span_s: float) -> float:
    """Frames per simulated second, which is what the clip is encoded at.

    The span is between the first frame and the last, so a capture of one
    frame has no span and no rate. Refused rather than defaulted: a rate
    invented here decides how fast the finished video appears to run.
    """
    if frames < 2:
        raise RecorderError(
            f"{frames} frame(s) captured. A clip needs at least two to have "
            f"a rate at all, and this one is the evidence that the capture "
            f"path works")
    if not math.isfinite(span_s) or span_s <= 0:
        raise RecorderError(
            f"{frames} frames arrived across {span_s!r} seconds of simulated "
            f"time. Without a span there is no rate that is not invented")
    rate = frames / span_s
    if rate < MIN_CAPTURE_HZ:
        raise RecorderError(
            f"the camera managed {rate:.2f} frames per simulated second over "
            f"{span_s:.1f} s. Under {MIN_CAPTURE_HZ:.0f} Hz the result is a "
            f"slideshow, and a rehearsal that accepted one would be telling "
            f"week 4 that the capture path works")
    return rate


def overlay_filter(text: str, font: str = FONT) -> str:
    """The drawtext filter that burns the run id into every frame.

    That burn is what makes an unrelated clip impossible to pass off as this
    run, so the receipt can bind the clip's hash to the record.
    """
    if not OVERLAY_RE.match(text or ""):
        raise RecorderError(
            f"overlay text {text!r} is not a run id. It goes into an ffmpeg "
            f"filter string where a colon or a backslash changes what the "
            f"filter means, so it is refused rather than escaped")
    return (f"drawtext=fontfile={font}:text={text}"
            f":x=24:y=24:fontsize=28:fontcolor=white"
            f":box=1:boxcolor=black@0.55:boxborderw=10")


def encode_command(frames_dir, clip, rate: float, width: int, height: int,
                   overlay: str, font: str = FONT) -> list:
    """The one ffmpeg invocation that turns the captured frames into the clip.

    `-framerate` before `-i` is the input rate and is the measured one.
    `-r` after it is the playback rate. Putting the measured rate in the
    second slot would drop or duplicate frames to reach it and the clip would
    cover a different amount of simulated time from the one it was captured
    over.
    """
    if not math.isfinite(rate) or rate <= 0:
        raise RecorderError(f"the capture rate is {rate!r}")
    frame_bytes(width, height)
    return [
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "rawvideo",
        "-pixel_format", "rgb24",
        "-video_size", f"{int(width)}x{int(height)}",
        "-framerate", f"{rate:.6f}",
        "-i", str(raw_path(frames_dir)),
        "-vf", overlay_filter(overlay, font),
        "-r", str(OUTPUT_FPS),
        "-pix_fmt", "yuv420p",
        "-c:v", "libx264",
        str(clip),
    ]


def clip_problems(clip, wanted_s: float, duration_s: float,
                  frames: int) -> list:
    """What is wrong with the finished clip, or an empty list.

    The rehearsal's own checker hashes the clip and reads its duration back
    out of ffprobe. This is the runner's earlier and cheaper answer, so a
    capture that produced nothing usable fails where the reason is still on
    screen rather than three checks later.
    """
    problems = []
    path = Path(clip)
    if not path.is_file():
        return [f"no clip at {path}"]
    size = path.stat().st_size
    if size < 1024:
        problems.append(f"the clip is {size} bytes, which is not a video")
    if frames < 2:
        problems.append(f"only {frames} frame(s) went into it")
    if math.isfinite(duration_s) and duration_s + 1e-6 < wanted_s:
        problems.append(
            f"the capture covers {duration_s:.1f} s of simulated time and "
            f"{wanted_s:.1f} s was asked for")
    return problems


def sweep(frames_dir) -> int:
    """Delete the captured frames. Returns the bytes reclaimed.

    They are an intermediate worth hundreds of megabytes and the clip is the
    artifact. Called after the encode has succeeded and never before it.
    """
    path = raw_path(frames_dir)
    try:
        size = path.stat().st_size
    except OSError:
        return 0
    try:
        path.unlink()
    except OSError:
        return 0
    return size


def receipt_fields(width: int, height: int, frames: int, span_s: float,
                   rate: float) -> dict:
    """What the run record says about the capture, for a human reading it."""
    return {
        "video_width": int(width),
        "video_height": int(height),
        "video_frames": int(frames),
        "video_span_sim_s": round(float(span_s), 3),
        "video_capture_hz": round(float(rate), 3),
        "video_playback_fps": OUTPUT_FPS,
        "video_source": f"gzserver camera sensor on {IMAGE_TOPIC}",
    }
